export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOG_OUT='LOG_OUT'
export const AUTH_LOADING = 'AUTH_LOADING'
export const GET_API_MODULE = 'GET_API_MODULE'